// Generated by Haxe TypeScript Declaration Generator :)

export class A {
	private constructor();
	static funfola(): string;
}

export namespace _Main {
	class Tipo_Impl_ {
		private constructor();
		static readonly a: string;
		static readonly b: string;
	}
}

export class Main {
	private constructor();
	static p(x: number): number;
	static dd(): void;
	static ee(x: string): void;
	static main(): void;
}

export namespace Main {
	function p(x: number): number;
}

export namespace Main {
	function ee(x: string): void;
}